export  const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT";
export const SIGNUP = "SIGNUP";
export const GET_USER_ON_AUTH_STATE_CHANGE = "GET_USER_ON_AUTH_STATE_CHANGE"
export const POST_PRODUCT = "POST_PRODUCT"
export const FETCH_PRODUCT = "FETCH_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"